from beam.utils.mock import MockAPI
# Import your Beam app
from app import app

# Load your app into the MockAPI
mocker = MockAPI(app)

# Call the API
print('ABOUT TO CALL API')
mocker.call(text="Welcome to our lesson today on understanding the key factors driving tensions between the Union and Confederacy of the United States that led to the civil war. To begin, let's talk about slavery in America. As early as 1619 African slaves were brought to Jamestown, Virginia and by 1860 enslaved people were primarily from West and Central Africa. This system of bondage created a deep divide between northern states which had abolished slavery by this time versus southern states who still relied heavily on slave labor for their economy thus creating tension between both sides that would eventually lead to civil war. (Pointing at slide image) You can see here an illustration of an enslaved person working on a cotton plantation which was common during this period of time.\nNow let's move onto racial prejudice & economic disparities which also played major roles in exacerbating tensions leading up to civil war. Racial prejudice was deeply entrenched throughout society with beliefs about white superiority over black people resulting in discriminatory laws being passed throughout the country limiting rights such as restrictions on voting or owning property etc.(Pointing at graph) Additionally you can see here a graph showing economic disparity between North & South where northerners felt like they were subsidizing southern slaveholders while southerners felt like they weren’t getting enough representation in Congress or having their interests adequately represented at a national level - further increasing tensions amongst regions leading up to conflict.\nFinally we come to what sparked actual physical confrontation - not only did political and social tensions continue rising, small confrontations and skirmishes began occurring between union states against confederacy forces with many seeing it as inevitable that full-scale combat would break out soon after (pointing at poster). Here we have an example propaganda poster from those times depicting how northerners were seen down south - these kinds of images helped fuel public opinion further escalating towards all out warfare", file_name="audio.wav")
